=== dini-ag-kim/amb/draft/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://w3id.org/kim/amb/draft/schemas/schema.json",
  "title": "OER",
  "description": "This is a generic JSON schema for describing an Open Educational Resource with schema.org",
  "type": "object",
  "default": {
    "@context": [
      "https://w3id.org/kim/amb/draft/context.jsonld",
      {
        "@language": "de"
      }
    ],
    "type": [
      "LearningResource"
    ]
  },
  "properties": {
    "@context": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/context.json"
    },
    "id": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/id.json"
    },
    "type": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/type.json"
    },
    "name": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/name.json"
    },
    "creator": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/creator.json"
    },
    "contributor": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/contributor.json"
    },
    "description": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/description.json"
    },
    "about": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/about.json"
    },
    "license": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/license.json"
    },
    "image": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/image.json"
    },
    "dateCreated": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/dateCreated.json"
    },
    "datePublished": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/datePublished.json"
    },
    "inLanguage": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/inLanguage.json"
    },
    "publisher": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/publisher.json"
    },
    "learningResourceType": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/learningResourceType.json"
    },
    "audience": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/audience.json"
    },
    "isBasedOn": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/isBasedOn.json"
    },
    "isPartOf": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/isPartOf.json"
    },
    "hasPart": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/hasPart.json"
    },
    "mainEntityOfPage": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/mainEntityOfPage.json"
    },
    "keywords": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/keywords.json"
    },
    "encoding": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/encoding.json"
    },
    "conditionsOfAccess": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/conditionsOfAccess.json"
    },
    "assesses": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/assesses.json"
    },
    "competencyRequired": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/competencyRequired.json"
    },
    "teaches": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/teaches.json"
    },
    "isAccessibleForFree": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/isAccessibleForFree.json"
    }
  },
  "required": [
    "@context",
    "id",
    "name",
    "type"
  ]
}

=== dini-ag-kim/amb/draft/examples/valid/affiliationOhneId.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "name": "Beispielressource",
  "id": "https://example.org/oer",
  "image": "https://example.org/oer/image.png",
  "type": ["LearningResource"],
  "creator": [
    {
      "name": "HansD",
      "type": "Person",
      "affiliation": {
        "id": "http://www.wikidata.org/entity/Q54096",
        "type": "Organization",
        "name": "Universität Köln"
      }
    },
    {
      "id": "https://example.org/bea-b",
      "name": "Bea B",
      "type": "Person",
      "affiliation": {
        "id": "https://ror.org/04xfq0f34",
        "type": "Organization",
        "name": "RWTH Aachen"
      }
    }
  ],
  "contributor": [
    {
      "name": "Caro C",
      "type": "Person",
      "affiliation": {
        "type": "Organization",
        "name": "TH Uni"
      }
    }
  ],
  "description": "Eine OER",
  "about": [
    {
      "id": "https://w3id.org/kim/hochschulfaechersystematik/n059"
    }
  ],
  "license": {
    "id": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  "dateCreated": "2019-07-03",
  "inLanguage": ["fr"],
  "publisher": [
    {
      "type": "Organization",
      "name": "Tutory",
      "id": "https://www.tutory.de"
    }
  ],
  "audience": [
    {
      "id": "http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/student"
    }
  ]
}

=== dini-ag-kim/amb/draft/examples/valid/tutoryExample.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "name": "Arbeitsblatt - Mon avenir - Französisch - tutory.de",
  "id": "https://www.tutory.de/w/fbbadf1a",
  "image": "https://www.tutory.de/worksheet/fbbadf1a-145a-463d-9a43-1ae9965c86b9.jpg?width=1000",
  "type": ["LearningResource"],
  "creator": [
    {
      "name": "HerunterS",
      "type": "Person"
    }
  ],
  "description": "Französisch-Arbeitsblatt",
  "about": [
    {
      "id": "http://w3id.org/kim/schulfaecher/s1009",
      "prefLabel": {
        "de": "Französisch"
      },
      "type": "Concept",
      "inScheme": {
        "id": "http://w3id.org/kim/schulfaecher/"
      }
    }
  ],
  "keywords": ["Französisch", "Niveau A2"],
  "learningResourceType": [
    {
      "id": "https://w3id.org/kim/hcrt/worksheet"
    },
    {
      "id": "http://w3id.org/openeduhub/vocabs/new_lrt/36e68792-6159-481d-a97b-2c00901f4f78"
    }
  ],
  "license": {
    "id": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  "conditionsOfAccess": {
    "id": "http://w3id.org/kim/conditionsOfAccess/no_login",
    "type": "Concept"
  },
  "dateCreated": "2019-07-02",
  "inLanguage": ["fr"],
  "publisher": [
    {
      "type": "Organization",
      "name": "Tutory",
      "id": "https://www.tutory.de"
    }
  ],
  "audience": [
    {
      "id": "http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/student",
      "prefLabel": {
        "en": "student"
      },
      "type": "Concept",
      "inScheme": {
        "id": "http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/"
      }
    }
  ]
}

=== dini-ag-kim/amb/20231019/examples/valid/highered-figure.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "id": "https://oer.gitlab.io/OS/figures/OS/hail_f0613_with_embedded_frame_nos.png",
  "type": [
    "LearningResource",
    "ImageObject"
  ],
  "name": "A-32 two-level page table",
  "creator": [
    {
      "id": "https://orcid.org/0000-0002-3064-147X",
      "type": "Person",
      "name": "Jens Lechtenb√∂rger",
      "honorificPrefix": "Dr."
    }
  ],
  "isAccessibleForFree": true,
  "license": {
    "id": "https://creativecommons.org/licenses/by-sa/4.0/"
  },
  "learningResourceType": [
    {
      "id": "https://w3id.org/kim/hcrt/image",
      "prefLabel": {
        "de": "Abbildung",
        "en": "Image"
      }
    }
  ],
  "isBasedOn": [
    {
      "id": "https://github.com/Max-Hailperin/Operating-Systems-and-Middleware--Supporting-Controlled-Interaction/blob/9fc6cbc76348fb091449741fac15e211776e8aba/hail_f0613.pdf",
      "name": "Figure 6.13",
      "creator": [
        {
          "type": "Person",
          "name": "Max Hailperin"
        }
      ],
      "license": {
        "id": "https://creativecommons.org/licenses/by-sa/3.0/"
      }
    }
  ],
  "isPartOf": [
    {
      "id": "https://oer.gitlab.io/OS/Operating-Systems-Memory-I.html",
      "type": [
        "LearningResource",
        "PresentationDigitalDocument"
      ],
      "name": "OS08: Virtual Memory I"
    }
  ]
}

=== dini-ag-kim/amb/draft/examples/valid/about-with-other-vocabulary.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "name": "Arbeitsblatt - Mon avenir - Französisch - tutory.de",
  "id": "https://www.tutory.de/w/fbbadf1a",
  "type": ["LearningResource"],
  "about": [
    {
      "id": "http://w3id.org/kim/schulfaecher/s1009",
      "prefLabel": {
        "de": "Französisch"
      },
      "type": "Concept",
      "inScheme": {
        "id": "http://w3id.org/kim/schulfaecher/"
      }
    },
    {
      "id": "http://example-subject-vocabulary.com/french"
    }
  ]
}

=== dini-ag-kim/amb/20230418/examples/valid/additionalContext.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    },
    "https://json-ld.org/contexts/person.jsonld"
  ],
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "type": [
    "LearningResource",
    "Course"
  ],
  "learningResourceType": [
    {
      "id": "https://w3id.org/kim/hcrt/course"
    }
  ]
}

=== dini-ag-kim/amb/20230418/examples/valid/parts.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "name": "Beispielressource",
  "id": "https://example.org/oer",
  "type": [
    "LearningResource"
  ],
  "creator": [
    {
      "name": "HansD",
      "type": "Person"
    }
  ],
  "isPartOf": [
    {
      "id": "https://example.org/broader",
      "type": [
        "LearningResource"
      ],
      "name": "Super-Ressource",
      "creator": [
        {
          "name": "Skye Blue",
          "type": "Person"
        }
      ],
      "license": "https://creativecommons.org/licenses/by/4.0/"
    }
  ],
  "hasPart": [
    {
      "id": "https://example.org/module",
      "type": [
        "LearningResource"
      ],
      "name": "Sub-Ressource",
      "creator": [
        {
          "name": "Skye Blue",
          "type": "Person"
        }
      ],
      "license": {
        "id": "https://creativecommons.org/licenses/by/4.0/"
      }
    }
  ]
}

=== dini-ag-kim/amb/20231019/examples/valid/videoWithoutContentUrl.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "type": ["LearningResource", "VideoObject"],
  "name": "The road ahead for network freedom",
  "inLanguage": ["en"],
  "id": "https://av.tib.eu/media/32641",
  "learningResourceType": [
    {
      "id": "https://w3id.org/kim/hcrt/video",
      "prefLabel": {
        "de": "Video",
        "en": "Video"
      }
    }
  ],
  "image": "https://av.tib.eu/thumbnail/32641",
  "encoding": [
    {
      "type": "MediaObject",
      "bitrate": "831",
      "embedUrl": "https://av.tib.eu/media/32641"
    }
  ]
}

=== dini-ag-kim/amb/draft/examples/valid/h5p-media-type.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "dateCreated": "2011-03-03",
  "datePublished": "2021-03-03",
  "type": ["Course", "LearningResource"],
  "encoding": [
    {
      "type": "MediaObject",
      "encodingFormat": "application/vnd.h5p+zip",
      "contentUrl": "https://example.oer.oer/h5p.zip"
    }
  ]
}
