=== dini-ag-kim/amb/draft/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://w3id.org/kim/amb/draft/schemas/schema.json",
  "title": "OER",
  "description": "This is a generic JSON schema for describing an Open Educational Resource with schema.org",
  "type": "object",
  "default": {
    "@context": [
      "https://w3id.org/kim/amb/draft/context.jsonld",
      {
        "@language": "de"
      }
    ],
    "type": [
      "LearningResource"
    ]
  },
  "properties": {
    "@context": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/context.json"
    },
    "id": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/id.json"
    },
    "type": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/type.json"
    },
    "name": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/name.json"
    },
    "creator": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/creator.json"
    },
    "contributor": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/contributor.json"
    },
    "description": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/description.json"
    },
    "about": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/about.json"
    },
    "license": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/license.json"
    },
    "image": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/image.json"
    },
    "dateCreated": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/dateCreated.json"
    },
    "datePublished": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/datePublished.json"
    },
    "inLanguage": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/inLanguage.json"
    },
    "publisher": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/publisher.json"
    },
    "learningResourceType": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/learningResourceType.json"
    },
    "audience": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/audience.json"
    },
    "isBasedOn": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/isBasedOn.json"
    },
    "isPartOf": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/isPartOf.json"
    },
    "hasPart": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/hasPart.json"
    },
    "mainEntityOfPage": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/mainEntityOfPage.json"
    },
    "keywords": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/keywords.json"
    },
    "encoding": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/encoding.json"
    },
    "conditionsOfAccess": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/conditionsOfAccess.json"
    },
    "assesses": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/assesses.json"
    },
    "competencyRequired": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/competencyRequired.json"
    },
    "teaches": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/teaches.json"
    },
    "isAccessibleForFree": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/isAccessibleForFree.json"
    }
  },
  "required": [
    "@context",
    "id",
    "name",
    "type"
  ]
}

=== dini-ag-kim/amb/draft/examples/valid/additionalContext.json
{
  "@context": [
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    {"@language": "de"},
    "https://json-ld.org/contexts/person.jsonld"
  ],
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "type": "Course",
  "learningResourceType": {
    "id": "https://w3id.org/kim/hcrt/course"
  }
}

=== dini-ag-kim/amb/20231019/examples/valid/addingToContext.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    },
    {
      "presentedAt": "http://purl.org/ontology/bibo/presentedAt"
    }
  ],
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "type": ["LearningResource", "Course"],
  "learningResourceType": [
    {
      "id": "https://w3id.org/kim/hcrt/course"
    }
  ]
}

=== dini-ag-kim/amb/draft/examples/valid/addingToContext.json
{
  "@context": [
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    {
      "@language": "de"
    },
    {
      "presentedAt": "http://purl.org/ontology/bibo/presentedAt"
    }
  ],
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "type": [
    "LearningResource",
    "Course"
  ],
  "learningResourceType": [
    {
      "id": "https://w3id.org/kim/hcrt/course"
    }
  ]
}

=== dini-ag-kim/amb/draft/examples/valid/mainEntityOf.json
{
  "@context": [
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "name": "Beispielressource",
  "id": "https://example.org/oer",
  "mainEntityOfPage": [
    {
      "id": "https://example.org/oer-description.html",
      "type": "Text",
      "provider": {
        "id": "https://oerworldmap.org/resource/urn:uuid:4062c64d-b0ac-4941-95c2-8116f137326d",
        "name": "ZOERR"
      },
      "dateCreated": "2020-01-01",
      "dateModified": "2020-02-02"
    }
  ],
  "image": "https://example.org/oer/image.png",
  "type": [
    "LearningResource"
  ],
  "creator": [
    {
      "name": "HansD",
      "type": "Person"
    }
  ],
  "description": "Eine OER",
  "about": [
    {
      "id": "https://w3id.org/kim/hochschulfaechersystematik/n059"
    }
  ],
  "license": "https://creativecommons.org/publicdomain/zero/1.0/legalcode",
  "dateCreated": "2019-07-03",
  "inLanguage": "fr",
  "publisher": [
    {
      "type": "Organization",
      "name": "Tutory",
      "id": "https://www.tutory.de"
    }
  ],
  "audience": [
    {
      "id": "http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/student"
    }
  ]
}

=== dini-ag-kim/amb/20230418/examples/valid/oerInMultipleLanguages.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "name": "Beispielressource",
  "id": "https://example.org/oer",
  "image": "https://example.org/oer/image.png",
  "type": [
    "LearningResource"
  ],
  "creator": [
    {
      "name": "HansD",
      "type": "Person"
    }
  ],
  "description": "Eine OER",
  "license": {
    "id": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  "dateCreated": "2019-07-03",
  "inLanguage": [
    "fr",
    "en",
    "de"
  ]
}

=== dini-ag-kim/amb/draft/examples/valid/concepts-as-object-with-uri-only.json
{
  "@context": [ 
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    {"@language": "de"}
  ],
    "name": "Beispielressource",
    "id": "https://example.org/oer",
    "image": "https://example.org/oer/image.png",
    "type": "CreativeWork",
    "creator": [
      {
        "name": "HansD",
        "type": "Person"
      }
    ],
    "description": "Eine OER",
    "about": [
      {
        "id": "https://w3id.org/kim/hochschulfaechersystematik/n059"
      }
    ],
    "license": "https://creativecommons.org/publicdomain/zero/1.0/legalcode",
    "dateCreated": "2019-07-03",
    "inLanguage": "fr",
    "publisher": [
      {
        "type": "Organization",
        "name": "Tutory",
        "id": "https://www.tutory.de"
      }
    ],
    "audience": [
      {
        "id": "http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/student"
      }
    ]
  }

=== dini-ag-kim/amb/20231019/examples/valid/competencies.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "type": ["Course", "LearningResource"],
  "assesses": [
    {
      "id": "https://example.org/competencies/1",
      "prefLabel": {
        "de": "Awesomeness"
      }
    }
  ],
  "competencyRequired": [
    {
      "id": "https://example.org/competencies/2",
      "prefLabel": {
        "de": "Humor"
      }
    }
  ],
  "teaches": [
    {
      "id": "https://example.org/competencies/3",
      "prefLabel": {
        "de": "Resilience"
      }
    }
  ]
}

=== dini-ag-kim/amb/draft/examples/valid/highered-course-part.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "id": "https://oer.gitlab.io/OS/Operating-Systems-Memory-I.html",
  "type": ["LearningResource", "PresentationDigitalDocument"],
  "name": "OS08: Virtual Memory I",
  "creator": [
    {
      "id": "https://orcid.org/0000-0002-3064-147X",
      "type": "Person",
      "name": "Jens Lechtenbörger",
      "honorificPrefix": "Dr."
    }
  ],
  "description": "A presentation on virtual memory in a course on Operating Systems (following the book Operating Systems and Middleware: Supporting Controlled Interaction by Max Hailperin). Learning objectives: Explain mechanisms and uses for virtual memory (including principle of locality and page fault handling as well as access of data on disk); Explain and perform address translation with page tables",
  "about": [
    {
      "id": "https://w3id.org/kim/hochschulfaechersystematik/n079",
      "prefLabel": {
        "de": "Informatik"
      },
      "type": "Concept"
    }
  ],
  "keywords": ["Computer Science", "Virtual Memory"],
  "isAccessibleForFree": true,
  "conditionsOfAccess": {
    "id": "http://w3id.org/kim/conditionsOfAccess/no_login",
    "type": "Concept"
  },
  "license": {
    "id": "https://creativecommons.org/licenses/by-sa/4.0/"
  },
  "image": "https://dini-ag-kim.github.io/amb/draft/img/os08-image.png",
  "dateCreated": "2020-06-25",
  "datePublished": "2020-06-29",
  "inLanguage": ["en"],
  "learningResourceType": [
    {
      "id": "https://w3id.org/kim/hcrt/slide",
      "prefLabel": {
        "de": "Präsentation",
        "en": "Presentation"
      }
    }
  ],
  "audience": [
    {
      "id": "http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/student",
      "prefLabel": {
        "en": "student"
      },
      "type": "Concept"
    }
  ],
  "isPartOf": [
    {
      "id": "https://oer.gitlab.io/OS",
      "type": ["LearningResource", "Course"],
      "name": "Computer Structures and Operating Systems"
    }
  ],
  "hasPart": [
    {
      "id": "https://oer.gitlab.io/OS/figures/OS/hail_f0613_with_embedded_frame_nos.png",
      "type": ["LearningResource", "ImageObject"],
      "name": "A-32 two-level page table"
    }
  ]
}
