=== dini-ag-kim/amb/draft/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://w3id.org/kim/amb/draft/schemas/schema.json",
  "title": "OER",
  "description": "This is a generic JSON schema for describing an Open Educational Resource with schema.org",
  "type": "object",
  "default": {
    "@context": [
      "https://w3id.org/kim/amb/draft/context.jsonld",
      {
        "@language": "de"
      }
    ],
    "type": [
      "LearningResource"
    ]
  },
  "properties": {
    "@context": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/context.json"
    },
    "id": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/id.json"
    },
    "type": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/type.json"
    },
    "name": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/name.json"
    },
    "creator": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/creator.json"
    },
    "contributor": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/contributor.json"
    },
    "description": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/description.json"
    },
    "about": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/about.json"
    },
    "license": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/license.json"
    },
    "image": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/image.json"
    },
    "dateCreated": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/dateCreated.json"
    },
    "datePublished": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/datePublished.json"
    },
    "inLanguage": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/inLanguage.json"
    },
    "publisher": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/publisher.json"
    },
    "learningResourceType": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/learningResourceType.json"
    },
    "audience": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/audience.json"
    },
    "isBasedOn": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/isBasedOn.json"
    },
    "isPartOf": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/isPartOf.json"
    },
    "hasPart": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/hasPart.json"
    },
    "mainEntityOfPage": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/mainEntityOfPage.json"
    },
    "keywords": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/keywords.json"
    },
    "encoding": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/encoding.json"
    },
    "conditionsOfAccess": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/conditionsOfAccess.json"
    },
    "assesses": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/assesses.json"
    },
    "competencyRequired": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/competencyRequired.json"
    },
    "teaches": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/teaches.json"
    },
    "isAccessibleForFree": {
      "$ref": "https://w3id.org/kim/amb/draft/schemas/isAccessibleForFree.json"
    }
  },
  "required": [
    "@context",
    "id",
    "name",
    "type"
  ]
}

=== dini-ag-kim/amb/20231019/examples/valid/conceptsAsObjectWithUriOnly.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "name": "Beispielressource",
  "id": "https://example.org/oer",
  "image": "https://example.org/oer/image.png",
  "type": ["LearningResource"],
  "creator": [
    {
      "name": "HansD",
      "type": "Person"
    }
  ],
  "description": "Eine OER",
  "about": [
    {
      "id": "https://w3id.org/kim/hochschulfaechersystematik/n059"
    }
  ],
  "license": {
    "id": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  "dateCreated": "2019-07-03",
  "inLanguage": ["fr"],
  "publisher": [
    {
      "type": "Organization",
      "name": "Tutory",
      "id": "https://www.tutory.de"
    }
  ],
  "audience": [
    {
      "id": "http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/student"
    }
  ]
}

=== dini-ag-kim/amb/draft/examples/valid/contributor.json
{
  "@context": [
    "https://w3id.org/kim/amb/draft/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "type": [
    "Course",
    "LearningResource"
  ],
  "datePublished": "2020-02-02",
  "contributor": [
    {
      "name": "Hans Dampf",
      "type": "Person",
      "id": "https://example.org/hansd"
    }
  ]
}

=== dini-ag-kim/amb/draft/examples/valid/learningResourceType-with-other-vocabulary.json
{
  "@context": [
    "https://w3id.org/kim/amb/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "type": ["LearningResource", "Course"],
  "publisher": [
    {
      "type": "Person",
      "name": "Maxima Mustermensch"
    }
  ],
  "learningResourceType": [
    {
      "id": "https://example-vocabular.com/course"
    },
    {
      "id": "https://w3id.org/kim/hcrt/course"
    },
    {
      "id": "http://w3id.org/openeduhub/vocabs/learningResourceType/course"
    }
  ]
}
